### ISSUE TITLE
Detection of opening times

### ISSUE THREAD

**Issue by golden-spiral** [OSM-de/WebToOSMOH#1]
http://steakhouse-wenigumstadt.de/ (bottom of page):

    Montag und Dienstag Ruhetag
    Mi- Sa ab 17.00 Uhr
    Sonn- und Feiertag Mittagstisch ab 11.30 bis 14.00 Uhr und ab 17 Uhr

http://bachgauer-hof.de/oeffnungszeiten.htm:
 Mo. - Sa. 16:30 - 22:00 Uhr So. 11:30 - 14:30 Uhr 16:30 - 22:00 Uhr Mi. & Do. Ruhetag 

Both lead to wrong detected strings.

**Comment by kmpoppe** [comment]
Danke @golden-spiral für den Hinweis. 
Ich habe das Tool erweitert - man kann nun direkt Inhalt von einer Website einfügen, und zwar so, dass die Formatierung erhalten bleibt. Das ist besonders wichtig bei Tabellen, da die "nur Text kopieren und einfügen"-Methode das Verarbeiten der Texte unmöglich gemacht hat.
Allerdings wird es erstmal nicht möglich sein, ein zufällig eingestreutes "Mittagstisch" oder "Küche" zu erkennen und das richtig zu trennen. Hierbei ist es unumgänglich, dass du beim Kopieren Dinge rauslässt, die das Script Überkopf schmeißen. Wir fackeln schon viel ab, einfach ausprobieren!
