### ISSUE TITLE
Convert button does not seem to work now

### ISSUE THREAD

**Issue by kevinp2** [OSM-de/WebToOSMOH#10]
I tried copying and pasting the hours from this web site:

https://www.24hourfitness.com/gyms/austin-tx/austin-sport

The Process button seems to work but the Convert button does not do anything.

You can try with this text:

```
Monday 05:00 AM - 10:00 PM 
Tuesday 05:00 AM - 10:00 PM
```

**Comment by kmpoppe** [comment]
Yeah, I completely revamped the script storage and forgot to update the site ...

Once Telekom gave me back my Internet -connection, I'll fix it.

Thanks for heads-up

Kai

**Comment by kmpoppe** [comment]
Resolved :-)
