### ISSUE TITLE
Security certificate expired?

### ISSUE THREAD

**Issue by Fizzie41** [OSM-de/WebToOSMOH#14]
Hi.

Just tried to open the site via Firefox, & got a security warning that the Certificate expired last week.

Was able to get into, but now unable to paste times in?

**Comment by kmpoppe** [comment]
Yeah, the certificate expires every 3 months as it's a free one. I correct that today.

**Comment by Fizzie41** [comment]
Thanks!

**Comment by kmpoppe** [comment]
Fixed
